package liqq.crk.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrkOutputExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public CrkOutputExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeIsNull() {
            addCriterion("output_time is null");
            return (Criteria) this;
        }

        public Criteria andOutputTimeIsNotNull() {
            addCriterion("output_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutputTimeEqualTo(Date value) {
            addCriterion("output_time =", value, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeNotEqualTo(Date value) {
            addCriterion("output_time <>", value, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeGreaterThan(Date value) {
            addCriterion("output_time >", value, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("output_time >=", value, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeLessThan(Date value) {
            addCriterion("output_time <", value, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeLessThanOrEqualTo(Date value) {
            addCriterion("output_time <=", value, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeIn(List<Date> values) {
            addCriterion("output_time in", values, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeNotIn(List<Date> values) {
            addCriterion("output_time not in", values, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeBetween(Date value1, Date value2) {
            addCriterion("output_time between", value1, value2, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputTimeNotBetween(Date value1, Date value2) {
            addCriterion("output_time not between", value1, value2, "outputTime");
            return (Criteria) this;
        }

        public Criteria andOutputNumIsNull() {
            addCriterion("output_num is null");
            return (Criteria) this;
        }

        public Criteria andOutputNumIsNotNull() {
            addCriterion("output_num is not null");
            return (Criteria) this;
        }

        public Criteria andOutputNumEqualTo(Integer value) {
            addCriterion("output_num =", value, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumNotEqualTo(Integer value) {
            addCriterion("output_num <>", value, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumGreaterThan(Integer value) {
            addCriterion("output_num >", value, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("output_num >=", value, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumLessThan(Integer value) {
            addCriterion("output_num <", value, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumLessThanOrEqualTo(Integer value) {
            addCriterion("output_num <=", value, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumIn(List<Integer> values) {
            addCriterion("output_num in", values, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumNotIn(List<Integer> values) {
            addCriterion("output_num not in", values, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumBetween(Integer value1, Integer value2) {
            addCriterion("output_num between", value1, value2, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputNumNotBetween(Integer value1, Integer value2) {
            addCriterion("output_num not between", value1, value2, "outputNum");
            return (Criteria) this;
        }

        public Criteria andOutputPriceIsNull() {
            addCriterion("output_price is null");
            return (Criteria) this;
        }

        public Criteria andOutputPriceIsNotNull() {
            addCriterion("output_price is not null");
            return (Criteria) this;
        }

        public Criteria andOutputPriceEqualTo(BigDecimal value) {
            addCriterion("output_price =", value, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceNotEqualTo(BigDecimal value) {
            addCriterion("output_price <>", value, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceGreaterThan(BigDecimal value) {
            addCriterion("output_price >", value, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("output_price >=", value, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceLessThan(BigDecimal value) {
            addCriterion("output_price <", value, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("output_price <=", value, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceIn(List<BigDecimal> values) {
            addCriterion("output_price in", values, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceNotIn(List<BigDecimal> values) {
            addCriterion("output_price not in", values, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("output_price between", value1, value2, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("output_price not between", value1, value2, "outputPrice");
            return (Criteria) this;
        }

        public Criteria andOutputTotalIsNull() {
            addCriterion("output_total is null");
            return (Criteria) this;
        }

        public Criteria andOutputTotalIsNotNull() {
            addCriterion("output_total is not null");
            return (Criteria) this;
        }

        public Criteria andOutputTotalEqualTo(BigDecimal value) {
            addCriterion("output_total =", value, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalNotEqualTo(BigDecimal value) {
            addCriterion("output_total <>", value, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalGreaterThan(BigDecimal value) {
            addCriterion("output_total >", value, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("output_total >=", value, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalLessThan(BigDecimal value) {
            addCriterion("output_total <", value, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("output_total <=", value, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalIn(List<BigDecimal> values) {
            addCriterion("output_total in", values, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalNotIn(List<BigDecimal> values) {
            addCriterion("output_total not in", values, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("output_total between", value1, value2, "outputTotal");
            return (Criteria) this;
        }

        public Criteria andOutputTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("output_total not between", value1, value2, "outputTotal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crk_output
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 03 09:02:17 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crk_output
     *
     * @mbg.generated Tue Dec 03 09:02:17 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}