package liqq.crk.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crk_output
 */
public class CrkOutput {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crk_output.id
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crk_output.product_id
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crk_output.create_time
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crk_output.output_time
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    private Date outputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crk_output.output_num
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    private Integer outputNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crk_output.output_price
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    private Long outputPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crk_output.output_total
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    private Long outputTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crk_output.id
     *
     * @return the value of crk_output.id
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crk_output.id
     *
     * @param id the value for crk_output.id
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crk_output.product_id
     *
     * @return the value of crk_output.product_id
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crk_output.product_id
     *
     * @param productId the value for crk_output.product_id
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crk_output.create_time
     *
     * @return the value of crk_output.create_time
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crk_output.create_time
     *
     * @param createTime the value for crk_output.create_time
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crk_output.output_time
     *
     * @return the value of crk_output.output_time
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public Date getOutputTime() {
        return outputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crk_output.output_time
     *
     * @param outputTime the value for crk_output.output_time
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public void setOutputTime(Date outputTime) {
        this.outputTime = outputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crk_output.output_num
     *
     * @return the value of crk_output.output_num
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public Integer getOutputNum() {
        return outputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crk_output.output_num
     *
     * @param outputNum the value for crk_output.output_num
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public void setOutputNum(Integer outputNum) {
        this.outputNum = outputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crk_output.output_price
     *
     * @return the value of crk_output.output_price
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public Long getOutputPrice() {
        return outputPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crk_output.output_price
     *
     * @param outputPrice the value for crk_output.output_price
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public void setOutputPrice(Long outputPrice) {
        this.outputPrice = outputPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crk_output.output_total
     *
     * @return the value of crk_output.output_total
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public Long getOutputTotal() {
        return outputTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crk_output.output_total
     *
     * @param outputTotal the value for crk_output.output_total
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    public void setOutputTotal(Long outputTotal) {
        this.outputTotal = outputTotal;
    }
}