package liqq.crk.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrkProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public CrkProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andProductBrandIsNull() {
            addCriterion("product_brand is null");
            return (Criteria) this;
        }

        public Criteria andProductBrandIsNotNull() {
            addCriterion("product_brand is not null");
            return (Criteria) this;
        }

        public Criteria andProductBrandEqualTo(String value) {
            addCriterion("product_brand =", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotEqualTo(String value) {
            addCriterion("product_brand <>", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandGreaterThan(String value) {
            addCriterion("product_brand >", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandGreaterThanOrEqualTo(String value) {
            addCriterion("product_brand >=", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLessThan(String value) {
            addCriterion("product_brand <", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLessThanOrEqualTo(String value) {
            addCriterion("product_brand <=", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLike(String value) {
            addCriterion("product_brand like", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotLike(String value) {
            addCriterion("product_brand not like", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandIn(List<String> values) {
            addCriterion("product_brand in", values, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotIn(List<String> values) {
            addCriterion("product_brand not in", values, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandBetween(String value1, String value2) {
            addCriterion("product_brand between", value1, value2, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotBetween(String value1, String value2) {
            addCriterion("product_brand not between", value1, value2, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("product_type like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("product_type not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductItemIsNull() {
            addCriterion("product_item is null");
            return (Criteria) this;
        }

        public Criteria andProductItemIsNotNull() {
            addCriterion("product_item is not null");
            return (Criteria) this;
        }

        public Criteria andProductItemEqualTo(String value) {
            addCriterion("product_item =", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemNotEqualTo(String value) {
            addCriterion("product_item <>", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemGreaterThan(String value) {
            addCriterion("product_item >", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemGreaterThanOrEqualTo(String value) {
            addCriterion("product_item >=", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemLessThan(String value) {
            addCriterion("product_item <", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemLessThanOrEqualTo(String value) {
            addCriterion("product_item <=", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemLike(String value) {
            addCriterion("product_item like", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemNotLike(String value) {
            addCriterion("product_item not like", value, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemIn(List<String> values) {
            addCriterion("product_item in", values, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemNotIn(List<String> values) {
            addCriterion("product_item not in", values, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemBetween(String value1, String value2) {
            addCriterion("product_item between", value1, value2, "productItem");
            return (Criteria) this;
        }

        public Criteria andProductItemNotBetween(String value1, String value2) {
            addCriterion("product_item not between", value1, value2, "productItem");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonIsNull() {
            addCriterion("suitable_season is null");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonIsNotNull() {
            addCriterion("suitable_season is not null");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonEqualTo(String value) {
            addCriterion("suitable_season =", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonNotEqualTo(String value) {
            addCriterion("suitable_season <>", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonGreaterThan(String value) {
            addCriterion("suitable_season >", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonGreaterThanOrEqualTo(String value) {
            addCriterion("suitable_season >=", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonLessThan(String value) {
            addCriterion("suitable_season <", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonLessThanOrEqualTo(String value) {
            addCriterion("suitable_season <=", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonLike(String value) {
            addCriterion("suitable_season like", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonNotLike(String value) {
            addCriterion("suitable_season not like", value, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonIn(List<String> values) {
            addCriterion("suitable_season in", values, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonNotIn(List<String> values) {
            addCriterion("suitable_season not in", values, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonBetween(String value1, String value2) {
            addCriterion("suitable_season between", value1, value2, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSeasonNotBetween(String value1, String value2) {
            addCriterion("suitable_season not between", value1, value2, "suitableSeason");
            return (Criteria) this;
        }

        public Criteria andSuitableSexIsNull() {
            addCriterion("suitable_sex is null");
            return (Criteria) this;
        }

        public Criteria andSuitableSexIsNotNull() {
            addCriterion("suitable_sex is not null");
            return (Criteria) this;
        }

        public Criteria andSuitableSexEqualTo(String value) {
            addCriterion("suitable_sex =", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexNotEqualTo(String value) {
            addCriterion("suitable_sex <>", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexGreaterThan(String value) {
            addCriterion("suitable_sex >", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexGreaterThanOrEqualTo(String value) {
            addCriterion("suitable_sex >=", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexLessThan(String value) {
            addCriterion("suitable_sex <", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexLessThanOrEqualTo(String value) {
            addCriterion("suitable_sex <=", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexLike(String value) {
            addCriterion("suitable_sex like", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexNotLike(String value) {
            addCriterion("suitable_sex not like", value, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexIn(List<String> values) {
            addCriterion("suitable_sex in", values, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexNotIn(List<String> values) {
            addCriterion("suitable_sex not in", values, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexBetween(String value1, String value2) {
            addCriterion("suitable_sex between", value1, value2, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andSuitableSexNotBetween(String value1, String value2) {
            addCriterion("suitable_sex not between", value1, value2, "suitableSex");
            return (Criteria) this;
        }

        public Criteria andProductSizeIsNull() {
            addCriterion("product_size is null");
            return (Criteria) this;
        }

        public Criteria andProductSizeIsNotNull() {
            addCriterion("product_size is not null");
            return (Criteria) this;
        }

        public Criteria andProductSizeEqualTo(String value) {
            addCriterion("product_size =", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotEqualTo(String value) {
            addCriterion("product_size <>", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeGreaterThan(String value) {
            addCriterion("product_size >", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeGreaterThanOrEqualTo(String value) {
            addCriterion("product_size >=", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeLessThan(String value) {
            addCriterion("product_size <", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeLessThanOrEqualTo(String value) {
            addCriterion("product_size <=", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeLike(String value) {
            addCriterion("product_size like", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotLike(String value) {
            addCriterion("product_size not like", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeIn(List<String> values) {
            addCriterion("product_size in", values, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotIn(List<String> values) {
            addCriterion("product_size not in", values, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeBetween(String value1, String value2) {
            addCriterion("product_size between", value1, value2, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotBetween(String value1, String value2) {
            addCriterion("product_size not between", value1, value2, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductColorIsNull() {
            addCriterion("product_color is null");
            return (Criteria) this;
        }

        public Criteria andProductColorIsNotNull() {
            addCriterion("product_color is not null");
            return (Criteria) this;
        }

        public Criteria andProductColorEqualTo(String value) {
            addCriterion("product_color =", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotEqualTo(String value) {
            addCriterion("product_color <>", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorGreaterThan(String value) {
            addCriterion("product_color >", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorGreaterThanOrEqualTo(String value) {
            addCriterion("product_color >=", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorLessThan(String value) {
            addCriterion("product_color <", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorLessThanOrEqualTo(String value) {
            addCriterion("product_color <=", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorLike(String value) {
            addCriterion("product_color like", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotLike(String value) {
            addCriterion("product_color not like", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorIn(List<String> values) {
            addCriterion("product_color in", values, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotIn(List<String> values) {
            addCriterion("product_color not in", values, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorBetween(String value1, String value2) {
            addCriterion("product_color between", value1, value2, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotBetween(String value1, String value2) {
            addCriterion("product_color not between", value1, value2, "productColor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crk_product
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 30 15:44:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}