package liqq.crk.dao.mysql;

import java.util.List;
import liqq.crk.model.CrkInput;
import liqq.crk.model.CrkInputExample;
import org.apache.ibatis.annotations.Param;

public interface CrkInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    long countByExample(CrkInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int deleteByExample(CrkInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int insert(CrkInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int insertSelective(CrkInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    List<CrkInput> selectByExample(CrkInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    CrkInput selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrkInput record, @Param("example") CrkInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int updateByExample(@Param("record") CrkInput record, @Param("example") CrkInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int updateByPrimaryKeySelective(CrkInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_input
     *
     * @mbg.generated Tue Dec 03 09:02:39 CST 2019
     */
    int updateByPrimaryKey(CrkInput record);
}