package liqq.crk.dao.mysql;

import java.util.List;
import liqq.crk.model.CrkOutput;
import liqq.crk.model.CrkOutputExample;
import org.apache.ibatis.annotations.Param;

public interface CrkOutputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    long countByExample(CrkOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int deleteByExample(CrkOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int insert(CrkOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int insertSelective(CrkOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    List<CrkOutput> selectByExample(CrkOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    CrkOutput selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrkOutput record, @Param("example") CrkOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int updateByExample(@Param("record") CrkOutput record, @Param("example") CrkOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int updateByPrimaryKeySelective(CrkOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_output
     *
     * @mbg.generated Sat Nov 30 15:47:06 CST 2019
     */
    int updateByPrimaryKey(CrkOutput record);
}