package liqq.crk.dao.mysql;

import java.util.List;
import liqq.crk.model.CrkProduct;
import liqq.crk.model.CrkProductExample;
import org.apache.ibatis.annotations.Param;

public interface CrkProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    long countByExample(CrkProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int deleteByExample(CrkProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int insert(CrkProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int insertSelective(CrkProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    List<CrkProduct> selectByExample(CrkProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    CrkProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrkProduct record, @Param("example") CrkProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int updateByExample(@Param("record") CrkProduct record, @Param("example") CrkProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int updateByPrimaryKeySelective(CrkProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crk_product
     *
     * @mbg.generated Sat Nov 30 15:44:37 CST 2019
     */
    int updateByPrimaryKey(CrkProduct record);
    
    /**
     * 按货号查询，时间倒序 商品
     * @param productItem
     * @return
     */
    List<CrkProduct> selectByItem(@Param("productItem") String productItem);
    /**
     * 按货号查询，时间倒序 入库
     * @param productItem
     * @return
     */
    List<CrkProduct> selectByInput(@Param("productItem") String productItem);
    /**
     * 按货号查询，时间倒序 入库
     * @param productItem
     * @return
     */
    List<CrkProduct> selectByOutput(@Param("productItem") String productItem);
    
}